### ISSUE TITLE
Please make async-cache compatible with recent lru-cache versions (7.x)

### ISSUE THREAD

**Issue by xanonid** [isaacs/async-cache#30]
It would be nice if async-cache could be used together with recent version of lru-cache.

Currently, upgrading to lru-cache 7.4 results in 16 failed tests of async-cache's test suite.

**Comment by isaacs** [comment]
How would you feel about just ditching this, and adding `await cache.fetch(key, fetchMethod)` to lru-cache?

Probably the `fetchMethod` would be better set as a cache option, since providing different fetchMethods with the same key will still return the same value, so you can't actually override it.  

Proof of concept here: https://github.com/isaacs/node-lru-cache/blob/isaacs/get-or-fetch-return-stale-while-fetching/index.js#L505

**Comment by isaacs** [comment]
Yeah, just use `lru-cache` v7.6 or higher, and provide an async `fetchMethod`.  Then you can call  `cache.fetch('key')` all day long, and it'll give you the same value that this module did.

This module doesn't need to exist any more.  Better to move off of it.
